#!/bin/sh
set -eux

tar --strip-components=1 -xf *
make defconfig V=1 HOSTCC="gcc -static"  
make -j$(nproc) \
  busybox \
  V=1 \
  HOSTCC="gcc -static" \
  PREFIX="/" \
  DESTDIR="$DESTDIR" \
  LDFLAGS="--static"
mkdir "$DESTDIR/bin"
cp ./busybox "$DESTDIR/bin"
for app in $(./busybox --list)
do
  ln -s busybox "$DESTDIR/bin/$app"
done